export const booksData = [
	{
		id: 1,
		name: 'JavaScript Everywhere',
		author: 'Adam D. Scottark Lutz',
		image: '/images/books/javascript_everywhere.png',
		price: 234,
	},
	{
		id: 2,
		name: 'Eloquent JavaScript',
		author: 'Marijn Haverbeke',
		image: '/images/books/eloquent_javascript.png',
		price: 134,
	},
	{
		id: 3,
		name: 'Learning React',
		author: 'Alex Banks & Eve Porcello ',
		image: '/images/books/learning_react.png',
		price: 234,
	},
	{
		id: 4,
		name: 'The C Programming Language',
		author: 'Brain W. Kernighan Dennis M. Ritchie',
		image: '/images/books/the_c.png',
		price: 332,
	},
	{
		id: 5,
		name: 'Effective TypeScript',
		author: 'Dan Vanderkam',
		image: '/images/books/effective_typescript.png',
		price: 132,
	},
	{
		id: 6,
		name: 'Python Crash Course',
		author: 'Eric Matthes',
		image: '/images/books/python_crash_course.png',
		price: 334,
	},
	{
		id: 7,
		name: 'The Road to React',
		author: 'Robin Wieruch ',
		image: '/images/books/the_road_to_react.png',
		price: 319,
	},
	{
		id: 8,
		name: 'Software Engineering at Google',
		author: 'Titus Winter',
		image: '/images/books/soft_eng_at_google.png',
		price: 342,
	},
	{
		id: 9,
		name: 'Learn JavaScript Quickly',
		author: 'Dan Vanderkam',
		image: '/images/books/learn_js_quickly.png',
		price: 132,
	},
];
